//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_EXPERT_SA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HABILIDADES
    {
        [Required(ErrorMessage = "El campo cédula es requerido")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "La cédula sólo puede contener números")]
        [StringLength(maximumLength: 9, ErrorMessage = "Cédula invalida", MinimumLength = 9)]
        public string cedulaEmpleadoPK { get; set; }
        public string habilidadPK { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
