//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace PI_EXPERT_SA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginCliente
    {
        [Required(ErrorMessage = "Nombre o cedula deben de ser digitados")]
        public string cedulaClientePK { get; set; }
        [Required(ErrorMessage = "Nombre o cedula deben de ser digitados")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "Debe de digitar una contraseña")]
        public string password { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
