//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_EXPERT_SA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTO()
        {
            this.MODULO = new HashSet<MODULO>();
            this.ROL = new HashSet<ROL>();
        }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "ID Proyecto:")]
        public int idProyectoPK { get; set; }

        [Display(Name = "Costo Estimado:")]
        public int costoEstimado { get; set; }

        [Display(Name = "Costo Real:")]
        public Nullable<int> costoReal { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Fecha de Inicio:")]
        public Nullable<System.DateTime> fechaInicio { get; set; }

        [Display(Name = "Fecha de Finalización:")]
        public Nullable<System.DateTime> fechaFin { get; set; }

        [Display(Name = "Duración Estimada:")]
        public Nullable<int> duracionEstimada { get; set; }

        [Display(Name = "Cliente:")]
        public string cedulaClienteFK { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Nombre:")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Objetivo:")]
        public string objetivo { get; set; }

        [Display(Name = "Duración Real:")]
        public Nullable<int> duracionReal { get; set; }

        [Display(Name = "Costo Estimado de Desarrollador por Hora:")]
        public Nullable<decimal> costoDesarrollador { get; set; }

        [Display(Name = "Líder:")]
        public string cedulaLiderFK { get; set; }

        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<MODULO> MODULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<ROL> ROL { get; set; }
        
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
