//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_EXPERT_SA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTO()
        {
            this.MODULO = new HashSet<MODULO>();
            this.ROL = new HashSet<ROL>();
        }

        [DisplayName("ID de Proyecto")]
        [Required(ErrorMessage = "Campo requerido")]
        //[DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int idProyectoPK { get; set; }

        [DisplayName("Costo Estimado")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Caracteres inválidos")]
        public decimal costoEstimado { get; set; }

        [DisplayName("Costo Real")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Caracteres inválidos")]
        public Nullable<decimal> costoReal { get; set; }

        [DisplayName("Fecha de Inicio")]
        [Required(ErrorMessage = "Campo requerido")]
        //[DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechaInicio { get; set; }

        [DisplayName("Fecha de Finalización")]
        [Required(ErrorMessage = "Campo requerido")]
        //[DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechaFin { get; set; }

        [DisplayName("Duración Estimada")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Caracteres inválidos")]
        public Nullable<int> duracionEstimada { get; set; }

        [DisplayName("Cliente")]
        [Required(ErrorMessage = "Campo requerido")]
        public string cedulaClienteFK { get; set; }

        [DisplayName("Nombre de Proyecto")]
        [StringLength(maximumLength: 64, MinimumLength = 1, ErrorMessage = "No puede introducir nombres de más de 64 caracteres")]
        [RegularExpression("^[a-zA-Z ]*$", ErrorMessage = "Caracteres inválidos")]
        [Required(ErrorMessage = "Campo requerido")]
        public string nombre { get; set; }

        [DisplayName("Objetivo")]
        [Required(ErrorMessage = "Campo requerido")]
        public string objetivo { get; set; }

        [DisplayName("Duración Real")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Caracteres inválidos")]
        public Nullable<int> duracionReal { get; set; }

        [DisplayName("Costo Desarrollador")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Caracteres inválidos")]
        public Nullable<decimal> costoDesarrollador { get; set; }

        [DisplayName("Líder")]
        [Required(ErrorMessage = "Campo requerido")]
        public string cedulaLiderFK { get; set; }

        public virtual CLIENTE CLIENTE { get; set; }

        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODULO> MODULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROL> ROL { get; set; }
    }
}
