//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_EXPERT_SA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class REQUERIMIENTO
    {
        public int idRequerimientoPK { get; set; }
        [Required]
        [Display(Name = "Modulo")]
        public int idModuloPK { get; set; }
        [Required]
        [Display(Name = "Proyecto")]
        public int idProyectoPK { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaEstado { get; set; }
        public string nombre { get; set; }
        public int complejidad { get; set; }
        //public Nullable<int> duracionEstimada { get; set; }
        public int duracionEstimada { get; set; }
        public string cedulaDesarrolladorFK { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual MODULO MODULO { get; set; }
    }
}
