//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_EXPERT_SA_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ROL
    {
        [Key]
        [Display(Name = "Cédula Líder")]
        [Required(ErrorMessage = "Campo requerido")]
        public string cedulaPK { get; set; }
        [Key]
        [Display(Name = "ID Proyecto")]
        public int idProyectoPK { get; set; }
        [Display(Name = "Tipo de rol")]
        [Required(ErrorMessage = "Campo requerido")]
        public string tipoRol { get; set; }
        [Display(Name = "Número de equipo")]
        [Required(ErrorMessage = "Campo requerido")]
        public int numEquipo { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
